//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Career
    {
        public int JobTitleId { get; set; }
        public string Position { get; set; }
        public string Experience { get; set; }
        public string Requirements { get; set; }
        public string Description { get; set; }
        public string Location { get; set; }
        public string City { get; set; }
        public System.DateTime CreatedDt { get; set; }
        public bool Status { get; set; }
        public string Qualification { get; set; }
        public string Department { get; set; }
        public string Package { get; set; }
        public string KeySkills { get; set; }
        public int Openings { get; set; }
    }
}
