//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GetBillDetail
    {
        public float Price { get; set; }
        public long OrderId { get; set; }
        public int ProductId { get; set; }
        public System.DateTime OrderDt { get; set; }
        public float DeliveryCharges { get; set; }
        public float DiscountAmt { get; set; }
        public float TotalAmt { get; set; }
        public string Name { get; set; }
        public float Qty { get; set; }
    }
}
