//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GetOrderDetail
    {
        public System.DateTime OrderDt { get; set; }
        public float TotalAmount { get; set; }
        public float DeliveryCharges { get; set; }
        public float DiscountAmt { get; set; }
        public float FinalAmount { get; set; }
        public byte PayMode { get; set; }
        public string PayRemark { get; set; }
    }
}
