//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceDetail
    {
        public long InvoiceDetailId { get; set; }
        public string Particulars { get; set; }
        public float Price { get; set; }
        public int Qty { get; set; }
        public long InvoiceId { get; set; }
    
        public virtual Invoice Invoice { get; set; }
    }
}
