//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoice()
        {
            this.InvoiceDetails = new HashSet<InvoiceDetail>();
        }
    
        public long InvoiceId { get; set; }
        public System.DateTime InvoiveDt { get; set; }
        public float Amount { get; set; }
        public float TaxAmount { get; set; }
        public float DiscountAmount { get; set; }
        public bool IsPaid { get; set; }
        public byte PayMode { get; set; }
        public float ReceivedAmt { get; set; }
        public long CustomerId { get; set; }
        public Nullable<int> CouponId { get; set; }
        public Nullable<long> BillNo { get; set; }
    
        public virtual DiscountCoupon DiscountCoupon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceDetail> InvoiceDetails { get; set; }
    }
}
