//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyDBContext : DbContext
    {
        public MyDBContext()
            : base("name=GardenDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Area> Areas { get; set; }
        public virtual DbSet<Banner> Banners { get; set; }
        public virtual DbSet<Career> Careers { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<DiscountCoupon> DiscountCoupons { get; set; }
        public virtual DbSet<Enquiry> Enquiries { get; set; }
        public virtual DbSet<Epamphlet> Epamphlets { get; set; }
        public virtual DbSet<FAQ> FAQs { get; set; }
        public virtual DbSet<InvoiceDetail> InvoiceDetails { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<OTP> OTPs { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<RecentUpdate> RecentUpdates { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<SubCategory> SubCategories { get; set; }
        public virtual DbSet<Tax> Taxes { get; set; }
        public virtual DbSet<TempCart> TempCarts { get; set; }
        public virtual DbSet<Testimonial> Testimonials { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
        public virtual DbSet<Visitor> Visitors { get; set; }
        public virtual DbSet<GetBillDetail> GetBillDetails { get; set; }
        public virtual DbSet<GetOrderDetail> GetOrderDetails { get; set; }
        public virtual DbSet<GetSaleProduct> GetSaleProducts { get; set; }
        public virtual DbSet<GetUserDetail> GetUserDetails { get; set; }
    }
}
