//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public long OrderId { get; set; }
        public System.DateTime OrderDt { get; set; }
        public string Email { get; set; }
        public string ShipName { get; set; }
        public string ShipAddress { get; set; }
        public string ShipCity { get; set; }
        public string ShipArea { get; set; }
        public string ShipPinCode { get; set; }
        public string ShipPhone { get; set; }
        public string BillName { get; set; }
        public string BillAddress { get; set; }
        public string BillCity { get; set; }
        public string BillArea { get; set; }
        public string BillPinCode { get; set; }
        public string BillPhone { get; set; }
        public byte PayMode { get; set; }
        public string PayRemark { get; set; }
        public Nullable<int> CouponId { get; set; }
        public float DeliveryCharges { get; set; }
        public float DiscountAmt { get; set; }
        public float TotalAmt { get; set; }
        public float TaxAmt { get; set; }
        public bool PaymentStatus { get; set; }
        public Nullable<int> User_UserId { get; set; }
        public string OrderStatus { get; set; }
        public string PaymentId { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
    
        public virtual DiscountCoupon DiscountCoupon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual User User { get; set; }
    }
}
