//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecentUpdate
    {
        public int UpdateId { get; set; }
        public string Title { get; set; }
        public System.DateTime UpdateDt { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public string Image1 { get; set; }
        public string Image2 { get; set; }
        public string Link { get; set; }
        public System.DateTime ScheduleDt { get; set; }
        public bool Status { get; set; }
        public Nullable<int> User_UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
