//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tax
    {
        public int TaxId { get; set; }
        public float CGST { get; set; }
        public float SGST { get; set; }
        public Nullable<float> VAT { get; set; }
        public Nullable<float> ServiceTax { get; set; }
    }
}
