//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Testimonial
    {
        public int TestimonialId { get; set; }
        public Nullable<System.DateTime> TestimonialDt { get; set; }
        public string CName { get; set; }
        public string Image { get; set; }
        public string Profession { get; set; }
        public string Organization { get; set; }
        public string Description { get; set; }
        public bool Status { get; set; }
    }
}
